#!/bin/bash
set -euo pipefail
export ORACLE_HOME="${ORACLE_HOME:-/opt/oracle/product/21c/dbhomeXE}"
export PATH="${ORACLE_HOME}/bin:/usr/bin:/bin:${PATH:-}"
OUT="${1:-/tmp/kehale_export}"
mkdir -p "$OUT"
CONN="${2:-system/Kehale2026!@//localhost:1521/XE}"

sqlplus -s "$CONN" <<SQL
SET COLSEP ','
SET PAGESIZE 0
SET FEEDBACK OFF
SET HEADING ON
SET UNDERLINE OFF
SET TRIMSPOOL ON
SET LINESIZE 32767
SET LONG 10000
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';
SPOOL ${OUT}/MBS_PAYMENTS.csv
SELECT BALADIEH_INTID, BUDGET_YEAR, PAYMENT_SEQ_YR, ACCEPT_SEQ_YR, ENTRY_DATE, PAY_TYPE, CHECK_NUM, PAY_DATE, AMOUNT, CASHIER, PRINTED, USER_ID, TRANS_DATE, EXPENSE_AUTH_BY, PAY_AUTH_BY, CASHING_DATE, ACTIVE, INACTIVE_REASON, INACTIVE_DATE, CHECK_DATE, TREASURY_RECEIPT_DATE, PARAGRAPH FROM MBSSMALL.MBS_PAYMENTS;
SPOOL OFF
SPOOL ${OUT}/MBS_PAY_ORDER.csv
SELECT BALADIEH_INTID, BUDGET_YEAR, PAYMENT_SEQ_YR, BENEFICIARY, NOTES, EXPENSE_AUTH_BY, ENTRY_DATE, PAY_AUTH_BY, PAY_DATE, AMOUNT, PAY_TYPE, CHECK_NUM, CASHIER, CASHING_DATE, PRINTED, USER_ID, TRANS_DATE, ACTIVE, INACTIVE_REASON, INACTIVE_DATE FROM MBSSMALL.MBS_PAY_ORDER;
SPOOL OFF
EXIT;
SQL

echo "Exported:"
ls -la "$OUT"
wc -l "$OUT"/*.csv
